# Moe global options

# List of any plugins to explicitly enable.
enable_plugins = ["disc_and_track", "media_encoding", "organize_extras"]

# Tells Moe where your music library resides.
library_path = "/home/alir/sandbox/tagged-by-moe"

# Whether or not to always set an album’s date to its original_date if present.
original_date = false

# Alters the location of files in your library.
[move]

# Whether or not to convert all filesystem paths to ASCII.
asciify_paths = false

# Album filesystem path format relative to the global configuration option, library_path.
album_path = "{album.artist}/{album.artist} - {album.title} ({album.year}) {{{album.label} {album.catalog_num}}} [{media_encoding(album)}]"

# Track filesystem path format relative to album_path.
track_path = "{disc_and_track(track, album)}. {track.title}{track.path.suffix}"

# Extra filesystem path format relative to album_path.
extra_path = "{organize_extras(extra)}"
